In [1]:
import pickle 
import numpy as np

In [2]:
pipe = pickle.load(open("pipe.pkl","rb"))

In [17]:
test_input = np.array([1,"male",16,1,0,45,"S"], dtype=object).reshape(1,7)  # pclass,sex,age,sibsp,parch,fare,embarked

In [18]:
test_input

array([[1, 'male', 16, 1, 0, 45, 'S']], dtype=object)

In [19]:
pipe.predict(test_input)

C:\Users\DELL PC\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL PC\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [20]:
test_input = np.array([1,"male",16,1,0,45,"C"], dtype=object).reshape(1,7)  # pclass,sex,age,sibsp,parch,fare,embarked

In [21]:
pipe.predict(test_input)

C:\Users\DELL PC\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL PC\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([1], dtype=int64)